"""add lead score

Revision ID: 619a408c2795
Revises: 0002_user_owned_listings
Create Date: 2026-06-11 18:00:35.130733

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '619a408c2795'
down_revision: str | None = '0002_user_owned_listings'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('lead_score', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'lead_score')
    # ### end Alembic commands ###
