"""add lead score

Revision ID: 93360a814c7f
Revises: 619a408c2795
Create Date: 2026-06-11 18:04:30.387074

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '93360a814c7f'
down_revision: str | None = '619a408c2795'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
